# Bandit configuration file for GEEST security scanning
# https://bandit.readthedocs.io/en/latest/config.html

exclude_dirs:
  - ./test
  - ./test/**

# Skip B101 (assert statements) as they are legitimate in test files
skips:
  - B101

# Note: All critical and medium severity issues have been resolved:
# - No shell injection vulnerabilities (B605 fixed)
# - XML parsing secured with defusedxml (B314 fixed)  
# - Debug interface restricted to localhost (B104 fixed)
# - All subprocess calls use safe array arguments
# - Try/except pass blocks are documented and acceptable
